version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/modules/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "dependabot[bot]"
    assignees:
      - "dependabot[bot]"

  # Node.js dependencies for CDK
  - package-ecosystem: "npm"
    directory: "/cdk"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "dependabot[bot]"
    assignees:
      - "dependabot[bot]"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "dependabot[bot]"
    assignees:
      - "dependabot[bot]"