# GitLab Runner ローカル設定ファイル
# ローカル環境でGitLab CI/CDパイプラインをテストするための設定

concurrent = 4
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

# Docker Executor設定
[[runners]]
  name = "local-docker-runner"
  url = "https://gitlab.com/"
  id = 1
  token = "local-test-token"
  token_obtained_at = 2024-01-01T00:00:00Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  
  [runners.docker]
    tls_verify = false
    image = "ubuntu:22.04"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = [
      "/var/run/docker.sock:/var/run/docker.sock",
      "/cache",
      "$PWD:$PWD:rw"
    ]
    shm_size = 0
    network_mode = "bridge"
    
    # 環境変数の設定
    environment = [
      "DOCKER_DRIVER=overlay2",
      "DOCKER_TLS_CERTDIR=",
      "LOCAL_TEST=true",
      "CI_DEBUG_TRACE=false"
    ]
    
    # リソース制限
    memory = "2g"
    memory_swap = "2g"
    cpus = "2"
    
    # セキュリティ設定
    security_opt = ["seccomp:unconfined"]
    cap_add = ["SYS_PTRACE"]

# Shell Executor設定（軽量テスト用）
[[runners]]
  name = "local-shell-runner"
  url = "https://gitlab.com/"
  id = 2
  token = "local-test-token-shell"
  token_obtained_at = 2024-01-01T00:00:00Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  
  [runners.shell]
    shell = "bash"
  
  [runners.cache]
    Type = "local"
    Path = ".gitlab-runner/cache"
    Shared = true

# Kubernetes Executor設定（オプション）
[[runners]]
  name = "local-kubernetes-runner"
  url = "https://gitlab.com/"
  id = 3
  token = "local-test-token-k8s"
  token_obtained_at = 2024-01-01T00:00:00Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "kubernetes"
  
  [runners.kubernetes]
    host = ""
    namespace = "gitlab-runner"
    privileged = false
    image = "ubuntu:22.04"
    
    # ボリューム設定
    [[runners.kubernetes.volumes.host_path]]
      name = "docker-sock"
      mount_path = "/var/run/docker.sock"
      host_path = "/var/run/docker.sock"
    
    [[runners.kubernetes.volumes.empty_dir]]
      name = "cache"
      mount_path = "/cache"