stages:
  - check
  - deploy

variables:
  AWS_DEFAULT_REGION: ap-northeast-1
  SERVICE_NAME: cicd-comparison
  STAGE_NAME: local
  CICD_TOOL: gitlab
  PYTHON_VERSION: "3.13"
  LOCALSTACK_ENDPOINT: http://localhost:4566
  AWS_ENDPOINT_URL: http://localhost:4566
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  SKIP_REAL_AWS_SERVICES: "true"
  SKIP_GITLAB_SAST: "true"
  SKIP_GITLAB_DEPENDENCY_SCANNING: "true"

before_script:
  - apt-get update -qq && apt-get install -y -qq git curl
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - export PATH="$HOME/.cargo/bin:$PATH"
  - uv sync --dev

lint:
  stage: check
  script:
    - uv run ruff check .
    - uv run black --check .

test:
  stage: check
  script:
    - uv run pytest --cov=modules/api --cov-report=xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

sca:
  stage: check
  script:
    - echo "SCA checks skipped in local environment"

sast:
  stage: check
  script:
    - echo "SAST checks skipped in local environment"

deploy-lambda:
  stage: deploy
  script:
    - echo "Lambda deployment skipped in local environment"
  only:
    - main

deploy-ecs:
  stage: deploy
  script:
    - echo "ECS deployment skipped in local environment"
  only:
    - main

deploy-ec2:
  stage: deploy
  script:
    - echo "EC2 deployment skipped in local environment"
  only:
    - main
