version: 0.0
os: linux
files:
  - source: modules/laravel/httpd_example.conf
    destination: /etc/httpd/conf.d/
  - source: modules/laravel/
    destination: /var/www/html
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: modules/laravel/deploys_scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: modules/laravel/deploys_scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: modules/laravel/deploys_scripts/application_start.sh
      timeout: 300
      runas: root
