version: 0.2

phases:
  install:
    commands:
      - bash codepipeline/buildspecs/common_install.sh

  pre_build:
    commands:
      - bash codepipeline/buildspecs/common_pre_build.sh --dev

  build:
    commands:
      - . codepipeline/buildspecs/common_env.sh
      - echo "キャッシュ作成とプロジェクト依存関係の準備..."
      - echo "Python依存関係をエクスポート（Amazon Inspector互換性のため）"
      - uv export --all-packages --no-dev --frozen --no-editable -o requirements.txt --no-emit-workspace --no-hashes --no-header

  post_build:
    commands:
      - echo "キャッシュ準備完了"

artifacts:
  files:
    - '**/*'

cache:
  key: cache-key-include-dev-$(codebuild-hash-files .tool-versions)-$(codebuild-hash-files package-lock.json)-$(codebuild-hash-files uv.lock)
  paths:
    - '/root/.cache/pip/**/*'
    - '/root/.cache/uv/**/*'
    - '/root/.cargo/**/*'
    - '/root/.npm/**/*'
    - '/root/.asdf/**/*'
    - '/root/.local/bin/**/*'
    - 'node_modules/**/*'
    - 'cdk/node_modules/**/*'