version: 0.2

phases:
  install:
    commands:
      - bash codepipeline/buildspecs/common_install.sh

  pre_build:
    commands:
      - bash codepipeline/buildspecs/common_pre_build.sh --dev

  build:
    commands:
      - . codepipeline/buildspecs/common_env.sh
      - echo "ユニットテストを実行中..."
      - cd modules/api
      - uv run pytest tests/ -v --tb=short --cov=. --cov-report=term-missing --cov-report=xml
      - cd ../..

  post_build:
    commands:
      - echo "ユニットテストが正常に完了しました"

artifacts:
  files:
    - modules/api/coverage.xml
  name: test-results

cache:
  key: cache-key-include-dev-$(codebuild-hash-files .tool-versions)-$(codebuild-hash-files package-lock.json)-$(codebuild-hash-files uv.lock)
  paths:
    - '/root/.cache/pip/**/*'
    - '/root/.cache/uv/**/*'
    - '/root/.cargo/**/*'
    - '/root/.npm/**/*'
    - '/root/.asdf/**/*'
    - '/root/.local/bin/**/*'
    - 'node_modules/**/*'
    - 'cdk/node_modules/**/*'